# fly.toml app configuration file generated for lennox-website on 2025-02-13T11:04:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lennox-website'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  DATABASE_URL = 'postgres://postgres:6TkqzmEZaj2KbyH@lennox-db.flycast:5432'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
